# Generated by Django 4.2.11 on 2025-02-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
