# Generated by Django 4.2.11 on 2025-02-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_city_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcrtype',
            name='abes_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
