# Generated by Django 4.2.11 on 2025-02-11 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_rcrtype_abes_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.region'),
        ),
    ]
