# Generated by Django 4.2.11 on 2025-02-11 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_alter_department_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcr',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.city'),
        ),
    ]
