# Generated by Django 4.2.11 on 2025-02-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_alter_city_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ppn',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
