# Generated by Django 4.2.11 on 2025-02-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_alter_book_author_alter_book_editor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
