# Generated by Django 4.2.11 on 2025-02-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_alter_book_publication_address_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
