# Generated by Django 4.2.11 on 2025-02-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_alter_editor_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
