# Generated by Django 4.2.11 on 2025-02-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_alter_author_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rcr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rest.rcr'),
        ),
    ]
