# Generated by Django 4.2.11 on 2025-02-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_book_rcr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
