# Generated by Django 4.2.11 on 2025-02-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcr',
            name='books_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
