# Generated by Django 4.2.11 on 2025-02-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_rcr_books_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcr',
            name='books_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
