# Generated by Django 4.2.11 on 2025-02-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_alter_rcr_books_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['firstname'], name='rest_author_firstna_a95fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['lastname'], name='rest_author_lastnam_5f6d91_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='rest_book_title_661ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='editor',
            index=models.Index(fields=['title'], name='rest_editor_title_69f6d7_idx'),
        ),
        migrations.AddIndex(
            model_name='rcr',
            index=models.Index(fields=['rcr_number'], name='rest_rcr_rcr_num_8074c9_idx'),
        ),
        migrations.AddIndex(
            model_name='rcr',
            index=models.Index(fields=['title'], name='rest_rcr_title_97f7a5_idx'),
        ),
    ]
