# Generated by Django 4.2.11 on 2025-02-18 08:55

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_author_rest_author_firstna_a95fa0_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='author',
            name='rest_author_firstna_a95fa0_idx',
        ),
        migrations.RemoveIndex(
            model_name='author',
            name='rest_author_lastnam_5f6d91_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='rest_book_title_661ec5_idx',
        ),
        migrations.RemoveIndex(
            model_name='editor',
            name='rest_editor_title_69f6d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='rcr',
            name='rest_rcr_rcr_num_8074c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='rcr',
            name='rest_rcr_title_97f7a5_idx',
        ),
        migrations.AddIndex(
            model_name='author',
            index=django.contrib.postgres.indexes.HashIndex(fields=['firstname'], name='rest_author_firstna_1dd285_hash'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=django.contrib.postgres.indexes.HashIndex(fields=['lastname'], name='rest_author_lastnam_581cde_hash'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.HashIndex(fields=['title'], name='rest_book_title_cdf35f_hash'),
        ),
        migrations.AddIndex(
            model_name='editor',
            index=django.contrib.postgres.indexes.HashIndex(fields=['title'], name='rest_editor_title_b0f4f1_hash'),
        ),
        migrations.AddIndex(
            model_name='rcr',
            index=django.contrib.postgres.indexes.HashIndex(fields=['rcr_number'], name='rest_rcr_rcr_num_029eaa_hash'),
        ),
        migrations.AddIndex(
            model_name='rcr',
            index=django.contrib.postgres.indexes.HashIndex(fields=['title'], name='rest_rcr_title_86b9e1_hash'),
        ),
    ]
