# Generated by Django 4.2.11 on 2025-02-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0017_remove_author_rest_author_firstna_a95fa0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcr',
            name='last_scraped_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rcr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='rest.rcr'),
        ),
    ]
