# Generated by Django 4.2.11 on 2025-02-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0018_rcr_last_scraped_date_alter_book_rcr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
