# Generated by Django 4.2.11 on 2025-02-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0019_alter_city_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='insee',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
