# Generated by Django 4.2.11 on 2025-02-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0020_city_insee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='title',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
