# Generated by Django 4.2.11 on 2025-02-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0021_alter_editor_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('firstname', 'lastname', 'type')},
        ),
    ]
