# Generated by Django 4.2.11 on 2025-02-24 15:49

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0022_alter_author_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booktype',
            index=django.contrib.postgres.indexes.HashIndex(fields=['label'], name='rest_bookty_label_007adc_hash'),
        ),
    ]
