# Generated by Django 4.2.11 on 2025-02-26 15:00

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0023_booktype_rest_bookty_label_007adc_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='RcrBookCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='booktranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='booktranslation',
            name='book',
        ),
        migrations.RemoveField(
            model_name='booktranslation',
            name='translate',
        ),
        migrations.AlterUniqueTogether(
            name='rcrbook',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rcrbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='rcrbook',
            name='rcr',
        ),
        migrations.AddIndex(
            model_name='rcrtype',
            index=django.contrib.postgres.indexes.HashIndex(fields=['label'], name='rest_rcrtyp_label_57b33c_hash'),
        ),
        migrations.DeleteModel(
            name='BookTranslation',
        ),
        migrations.DeleteModel(
            name='RcrBook',
        ),
        migrations.AddField(
            model_name='rcrbookcount',
            name='rcr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.rcr'),
        ),
    ]
