# Generated by Django 4.2.11 on 2025-02-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0024_rcrbookcount_alter_booktranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='translated_as',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='translated_of',
            field=models.TextField(blank=True, null=True),
        ),
    ]
