# Generated by Django 4.2.11 on 2025-02-26 15:50

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0025_book_translated_as_book_translated_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.HashIndex(fields=['tag'], name='rest_bookta_tag_28e45d_hash')],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='rest.booktags'),
        ),
    ]
