# Generated by Django 4.2.11 on 2025-03-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0026_booktags_book_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ppn',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, to='rest.booktags'),
        ),
    ]
