# Generated by Django 4.2.11 on 2025-03-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0027_alter_book_ppn_alter_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='unique_identifier',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
