# Generated by Django 4.2.11 on 2024-06-07 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(db_column='code', max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Rcr',
            fields=[
                ('rcr', models.CharField(db_column='rcr', max_length=15, primary_key=True, serialize=False)),
                ('lib', models.CharField(max_length=200)),
                ('iln', models.IntegerField()),
                ('ppn', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('physical_addr_1', models.CharField(blank=True, max_length=300, null=True)),
                ('physical_addr_2', models.CharField(blank=True, max_length=300, null=True)),
                ('physical_addr_3', models.CharField(blank=True, max_length=300, null=True)),
                ('physical_addr_4', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('cedex', models.CharField(blank=True, max_length=15, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'rcr',
            },
        ),
        migrations.CreateModel(
            name='SudocQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('number', models.IntegerField(db_column='number')),
                ('created', models.DateField(auto_now_add=True)),
                ('lan', models.ForeignKey(db_column='lan', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.language')),
                ('rbc', models.ForeignKey(db_column='rbc', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.rcr')),
            ],
            options={
                'db_table': 'sudoc_query',
            },
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['code'], name='language_code_5bf85d_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['name'], name='language_name_7453bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='sudocquery',
            constraint=models.UniqueConstraint(fields=('rbc', 'lan', 'created'), name='unique_rbc_lan_created'),
        ),
    ]
