DOCKER_COMP = docker compose

up: ## Start the docker hub in detached mode (no logs)
	@$(DOCKER_COMP) up --detach

build: ## Build the docker hub
	@$(DOCKER_COMP) build

stop: ## Stop the docker hub
	@$(DOCKER_COMP) stop


